### ISSUE TITLE
Unable to build and run app with cli command

### ISSUE THREAD

**Issue by LouisMarotta** [LemmurOrg/lemmur#345]
### Device info

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.7.0-10.0.pre.61, on Ubuntu 22.10 6.1.0-0.1-liquorix-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] Android Studio
[✓] VS Code (version 1.74.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

### Describe the bug

Trying to compile the app (both for Android and Linux) through cli gives me an error regarding the localization syntax, but if i but building for Linux (only on x86, ARM gives the same error) with the VSCode run command it runs with no problems

### Steps to reproduce

1. Compile app with ```flutter run linux --flavor dev --target lib/main_dev.dart``` or ```flutter build linux --target lib/main_prod.dart```
2. See error

### Relevant logs

<details>
  <summary>Command Output</summary>
  
 ```
 [intl_hi.arb:number_of_comments] ICU Syntax Error: Expected "identifier" but found "{".
    {formattedCount,plural, =1{{{ count }} टिप्पणी (कमेंट )} other{{{ count }} टिप्पणियाँ (कोम्मेंट्स )}}
                                ^
Exception: Found syntax errors.
Launching lib/main_dev.dart on Linux in debug mode...
ERROR: [intl_hi.arb:number_of_comments] ICU Syntax Error: Expected "identifier" but found "{".
ERROR: Target gen_localizations failed: Exception: Found syntax errors.
Building Linux application...                                           
Unhandled exception:
Crash when compiling:
RangeError (index): Invalid value: Only valid value is 0: 1

#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      Class._computeOnClause (package:kernel/ast.dart:1129:73)
#2      Class.onClause (package:kernel/ast.dart:1112:49)
#3      SourceClassBuilder.checkMixinApplication (package:front_end/src/fasta/source/source_class_builder.dart:905:52)
#4      SourceLoader.checkMixins (package:front_end/src/fasta/source/source_loader.dart:2424:19)
#5      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:533:14)
<asynchronous suspension>
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:408:33)
<asynchronous suspension>
#8      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:68:50)
<asynchronous suspension>
#9      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:568:11)
<asynchronous suspension>
#10     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1216:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Exception: Build process failed
```

[Pastebin with verbose output](https://pastebin.com/8pVpi1WT)
</details>

**Comment by LouisMarotta** [comment]
I just realized I was using the master branch of Flutter, downgrading to stable fixed it.
